### PR TITLE
fix file_content path

### PR DESCRIPTION
**Pull request by ekersten**
file_content was trying to fetch the wrong file path. This fixes that.

### CODE REVIEW

**Comment by ekersten** [comment]
I've also changed the upload path to svg to make it cleaner.

Printing the `file_content` on a template still requires the `safe` filter but I find that acceptable

**Comment by Aleksi44** [comment]
Hi @ekersten 

Thanks for this pull request.

Some comments :

- I think the `upload_to` value should be filled in from Django's settings.py. Something like `SVG_FOLDER_UPLOAD_TO = 'svg'` (with 'media' as default value if it's not set)
- Change of `upload_to` break updates. If someone wanted to update this package (mix between files/folders)

What do you think?

**Comment by ekersten** [comment]
Sounds reasonable. 

I've created a setting called `WAGTAILSVG_UPLOAD_FOLDER` and it defaults to `media`

**Comment by Aleksi44** [comment]
Merged here :

```
wagtailsvg==0.0.19
```

I updated the README and cleaned up the code a bit.

Thanks @ekersten

**Pull request merged**
